changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot

  categories:
    - title: "🚀 Features"
      labels:
        - feature
        - enhancement

    - title: "🐛 Bug fixes"
      labels:
        - bug
        - fix

    - title: "🎨 Interface and usability"
      labels:
        - ui
        - ux

    - title: "⚙️ Engineering and maintenance"
      labels:
        - ci
        - dependencies
        - maintenance
        - refactor

    - title: "📚 Documentation"
      labels:
        - documentation

    - title: "Other changes"
      labels:
        - "*"
